writeLogs: true

settings:
  # Сообщение о получении прогресса
  quest_progress: "actionbar:&8[&e!&8] &7Прогресс &e{quest} &a+{progress}&7/&e{required}"
  # Форматы прогресса
  progress_formatter_compact_progress_format: "&7○ {objective} &e{percentage}"
  progress_formatter_compact_complete_format: "&a✓ {objective} &e100%"
  progress_formatter_progress_format: "&7○ {goal} &e{current}&7/&e{required} &e{percentage}"
  progress_formatter_complete_format: "&a✓ {goal}"
  progress_formatter_goals_undefined: "Неизвестная цель"

objective_formats:
  TRADE_VILLAGER: "Торговля с жителями"
  EXP_CHANGE: "Получено опыта"
  PLAYTIME: "Наиграно"
  SURVIVAL_CONDITION: "Выжить {conditions}"
  BLOCK_SHIELD: "Заблокировано щитом"
  CURE_VILLAGER: "Вылечено жителей"
  USE_TOTEM: "Использовано тотемов"
  SHEAR_SHEEP: "Подстрижено овец"
  TNT_BREAK_BLOCKS: "Взорвано блоков"
  COLLECT_FROM_COMPOSTER: "Собрано из компостера"
  FILL_COMPOSTER: "Заполнено компостер"
  RESURRECT_DRAGON: "Возрождено драконов"
  IGNITE_TNT: "Поджечь динамит"
  USE_GRINDSTONE_ITEM: "Использовано точило"
  DEATH: "Смертей"
  MOVE: "Пройдено блоков"
  RIDE_HORSE: "Проехать на лошади"
  ANVIL: "Использовано наковальню"
  ENCHANT: "Зачаровано предметов"
  ENCHANT_WITH_LEVEL: "Зачаровать {item} с уровнем {level}"
  CATCH_FISH: "Поймано рыбы"
  BLOCK_DAMAGE_SHIELD: "Заблокировано урона щитом"
  USE_FURNACE: "Использовано печь"
  PREREQUISITE_QUEST: "Пройти поручение {quest} у {target}"