name: QuestLibrary
version: '${project.version}'
main: ru.nilsson03.library.quest.QuestLibrary
api-version: 1.16
authors: [Nilsson03]
description: "The library for integration of quests into plugins."